#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyAppTest.Resource", IsApplication=true)]

namespace MyAppTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int bottom_tab_font_size = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int bottom_tab_padding_drawable = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int bottom_tab_padding_up = 2130968577;
			
			// aapt resource value: 0x7f04000e
			public const int emotion_item_view_height = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int large_padding_length = 2130968582;
			
			// aapt resource value: 0x7f04000d
			public const int new_blog_size = 2130968589;
			
			// aapt resource value: 0x7f040013
			public const int no_result_padding_length = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int normal_padding_length = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int splash_test_center_margin_right = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int splash_test_top_margin_top = 2130968591;
			
			// aapt resource value: 0x7f040005
			public const int sta_height = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int switch_logo_bottom_padding = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int title_height = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int title_text_size = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int widget_content_margin_left = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int widget_content_margin_top = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int widget_height = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int widget_logo_size = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int widget_write_margin_left = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int widget_write_margin_top = 2130968583;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int a2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Bells = 2130837506;
			
			// aapt resource value: 0x7f02001b
			public const int black = 2130837531;
			
			// aapt resource value: 0x7f020003
			public const int home_btn_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int home_btn_bg_d = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int home_btn_bg_n = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int home_btn_bg_s = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_1_d = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_1_n = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_2_d = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon_2_n = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int icon_3_d = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int icon_3_n = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int icon_4_d = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_4_n = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_5_d = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_5_n = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Kerry = 2130837522;
			
			// aapt resource value: 0x7f02001f
			public const int list_background = 2130837535;
			
			// aapt resource value: 0x7f020019
			public const int ltgray = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ltyellow = 2130837530;
			
			// aapt resource value: 0x7f020013
			public const int maintab_toolbar_bg = 2130837523;
			
			// aapt resource value: 0x7f020021
			public const int namcard_picker_bkg_hover = 2130837537;
			
			// aapt resource value: 0x7f020020
			public const int namcard_picker_bkg_normal = 2130837536;
			
			// aapt resource value: 0x7f020014
			public const int red_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int state1 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int state2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int state3 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int state4 = 2130837528;
			
			// aapt resource value: 0x7f02001c
			public const int transparent = 2130837532;
			
			// aapt resource value: 0x7f02001e
			public const int transparent_background = 2130837534;
			
			// aapt resource value: 0x7f02001d
			public const int widget_edit_block_bg_normal = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int OtherReason = 2131165191;
			
			// aapt resource value: 0x7f070015
			public const int Password = 2131165205;
			
			// aapt resource value: 0x7f07000d
			public const int Text = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int UserName = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int account = 2131165203;
			
			// aapt resource value: 0x7f070027
			public const int btnAlert = 2131165223;
			
			// aapt resource value: 0x7f07000a
			public const int btnClose = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int btnConfirm = 2131165193;
			
			// aapt resource value: 0x7f070017
			public const int btnLogin = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int btnState = 2131165213;
			
			// aapt resource value: 0x7f070016
			public const int checkBox1 = 2131165206;
			
			// aapt resource value: 0x7f07000c
			public const int imageView1 = 2131165196;
			
			// aapt resource value: 0x7f070010
			public const int imgUser = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int lblListHeader = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int lblListItem = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout1 = 2131165192;
			
			// aapt resource value: 0x7f07001e
			public const int linearLayout2 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout3 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int linearLayout4 = 2131165217;
			
			// aapt resource value: 0x7f070024
			public const int linearLayout5 = 2131165220;
			
			// aapt resource value: 0x7f07000b
			public const int listView1 = 2131165195;
			
			// aapt resource value: 0x7f070028
			public const int listView2 = 2131165224;
			
			// aapt resource value: 0x7f07001c
			public const int lvExp = 2131165212;
			
			// aapt resource value: 0x7f070018
			public const int main_radio = 2131165208;
			
			// aapt resource value: 0x7f070001
			public const int radioButton1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int radioButton2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int radioButton3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int radioButton4 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int radioButton5 = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int radioGroup1 = 2131165184;
			
			// aapt resource value: 0x7f070019
			public const int radio_button0 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int radio_button1 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int radio_button2 = 2131165211;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int textView2 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int textView3 = 2131165199;
			
			// aapt resource value: 0x7f070022
			public const int textView4 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int textView6 = 2131165221;
			
			// aapt resource value: 0x7f070023
			public const int txtMissionName = 2131165219;
			
			// aapt resource value: 0x7f070020
			public const int txtMissionNum = 2131165216;
			
			// aapt resource value: 0x7f070026
			public const int txtPlateNum = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AlertItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AlertList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CallService = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Customlayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HeaderCustomLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListItemCustomLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Maintabs = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MissionList = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PointItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PointList = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int main_friends = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int main_home = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int main_manage_date = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int main_news = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int more = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int button_text = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int main_tab_bottom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
